### ISSUE TITLE
XML::Loy::XRD test fails with Mojolicious 5.77

### ISSUE THREAD

**Issue by reneeb** [Akron/XML-Loy#1]
```
Can't call method "at" on an undefined value at lib/XML/Loy/XRD.pm line 347, <DATA> line 2231.
```

It's this test 

```
is_deeply(
    decode_json($xrd->to_json),
    { links =>
    [ { rel => 'foo' } ] =>
      properties =>
        { bar  => 'foo' } },
    'Correct JRD');
```

The only change with Mojo::DOM I can see is https://github.com/kraih/mojo/commit/7f1338344cccc79c8490ff9088cc8709c2afe8ff

**Comment by Akron** [comment]
Hi Renee, finally I had time to look into this issue (I saw in on CPANTesters earlier). The problem originates still on the old wrong root element vs. node bug sri fixed in recent versions of Mojo::DOM. I think I have to go through the whole XML::Loy code to update the root handling to the now corrected system of Mojo::DOM. I expect to have quite a lot of legacy code in there to circumvent the old behaviour that can now be removed.

Thanks for reporting - fixed in [0.36](https://github.com/Akron/XML-Loy/commit/b07bf8c3971792cddaf881f13594b53bab5fb6b4)! I added you as a contributor.
